---
image:
  tag: latest
config:
  secretKey: "secretValue"
  postgres:
    secretReferenceKey: safe-transaction-postgres
  redis:
    secretReferenceKey: safe-transaction-redis
    storageClassName: ceph-ephimeral
  rabbitmq:
    secretReferenceKey: safe-transaction-rabbitmq
persistence:
  storageClassName: ceph-ephimeral