---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "safe-transaction.fullname" . }}-web
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "safe-transaction.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- .Values.commonLabels | toYaml | nindent 4 }}
    {{- end }}
{{- if .Values.commonAnnotations }}
  annotations:
    {{- .Values.commonAnnotations | toYaml | nindent 4 }}
{{- end }}
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    type: {{ .Values.strategy }}
  selector:
    matchLabels:
      app.kubernetes.io/component: web
      app.kubernetes.io/instance: {{ include "safe-transaction.name" . }}
      app.kubernetes.io/name: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: web
        app.kubernetes.io/instance: {{ include "safe-transaction.name" . }}
        app.kubernetes.io/name: {{ .Release.Name }}
    spec:
      containers:
      - name: web
        image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: [ docker/web/run_web.sh ]
        workingDir: /app
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          seccompProfile: 
            type: RuntimeDefault
          capabilities:
            drop:
            - ALL
        {{- if .Values.resources }}
        resources: {{- toYaml .Values.resources | nindent 12 }}
        {{- else }}
        resources:
          limits:
            cpu: 2
            memory: 4G
          requests:
            cpu: 1
            memory: 2G
        {{- end }}
        envFrom:
          - configMapRef:
              name: {{ include "safe-transaction.fullname" . }}
          - secretRef:
              {{- if .Values.config.refSecretKey }}
              name: {{ .Values.config.refSecretKey }}
              {{- else }}
              name: {{ include "safe-transaction.fullname" . }}
              {{- end }}
          - secretRef:
              name: {{ include "safe-transaction.postgres-secret" . }}
          - secretRef:
              name: {{ include "safe-transaction.redis-secret" . }}
          - secretRef:
              name: {{ include "safe-transaction.rabbitmq-secret" . }}
        ports:
        - containerPort: {{ .Values.service.ports.number }}
          name: {{ .Values.service.ports.name }}
          protocol: TCP
        volumeMounts:
          - name: content-volume
            mountPath: /nginx
          - name: tmp-volume
            mountPath: /tmp
      serviceAccountName: {{ include "safe-transaction.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: content-volume
          persistentVolumeClaim:
            claimName: {{ include "safe-transaction.fullname" . }}
        - name: tmp-volume
          emptyDir: {} 

