---
{{- $existingPostgresSecretObj := (lookup "v1" "Secret" .Release.Namespace .Values.config.postgres.secretReferenceKey) | default dict }}
{{- $existingPostgresSecretData := (get $existingPostgresSecretObj "data" | default dict ) }}
{{- $postgresUsername := (get $existingPostgresSecretData "username" | b64dec ) | default (.Values.config.postgres.username ) }}
{{- $postgresPassword := (get $existingPostgresSecretData "password" | b64dec ) | default (.Values.config.postgres.password ) }}
{{- $existingRedisSecretObj := (lookup "v1" "Secret" .Release.Namespace .Values.config.redis.secretReferenceKey) | default dict }}
{{- $existingRedisSecretData := (get $existingRedisSecretObj "data" | default dict ) }}
{{- $redisPassword := (get $existingRedisSecretData "password" | b64dec ) | default (.Values.config.redis.password ) }}
{{- $existingRabbitmqSecretObj := (lookup "v1" "Secret" .Release.Namespace .Values.config.rabbitmq.secretReferenceKey) | default dict }}
{{- $existingRabbitmqSecretData := (get $existingRabbitmqSecretObj "data" | default dict ) }}
{{- $rabbitmqUsername := (get $existingRabbitmqSecretData "username" | b64dec ) | default (.Values.config.rabbitmq.username ) }}
{{- $rabbitmqPassword := (get $existingRabbitmqSecretData "password" | b64dec ) | default (.Values.config.rabbitmq.password ) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "safe-transaction.fullname" . }}-integrations
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "safe-transaction.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- .Values.commonLabels | toYaml | nindent 4 }}
    {{- end }}
{{- if .Values.commonAnnotations }}
  annotations:
    {{- .Values.commonAnnotations | toYaml | nindent 4 }}
{{- end }}
type: Opaque
data:
  # Format: psql://postgres:postgres@txs-db:5432/postgres
  DATABASE_URL: "{{- printf "psql://%s:%s@%s:%s/%s" $postgresUsername $postgresPassword .Values.config.postgres.host .Values.config.postgres.port .Values.config.postgres.database | b64enc -}}"
  # Format redis://redis-ha.redis.svc.cluster.stage:6379/0 
  REDIS_URL: "{{- printf "redis://%s@%s:%s/%s" $redisPassword .Values.config.redis.host .Values.config.redis.port .Values.config.redis.database | b64enc -}}"
  # Format amqp://<user>:<password>@rabbitmq-ha-cluster/safe  
  CELERY_BROKER_URL: "{{- printf "amqp://%s:%s@%s/%s" $rabbitmqUsername $rabbitmqPassword .Values.config.rabbitmq.host .Values.config.rabbitmq.virtualHost | b64enc -}}"

